branches:
  only:
    - master
    - develop
sudo: required
dist: trusty
language: python
python:
  - 3.4
jdk:
  - openjdk7
before_script:
  - sudo apt-get update -qq
  - sudo apt-get -y install openjdk-7-jdk openjdk-7-jre
script:
  - echo "Running Unittests"
# - cd util/unittests
#  - coverage erase
#  - coverage run --omit='/usr/local/lib/python3.4/*' --include='../*.py' --parallel-mode ../../my_module/main.py --help
#  - coverage combine
after_success:
  coveralls
notifications:
  email: false
